const books = [
  {
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    description: "A practical guide to building good habits and breaking bad ones.",
    coverImage: "",
    rating: 4.8,
    price: 499,
    status: "Available",
    featured: true,
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Fiction",
    description: "A story about following your dream and discovering your destiny.",
    coverImage: "",
    rating: 4.7,
    price: 399,
    status: "Available",
    featured: true,
  },
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    genre: "Tech",
    description: "A guide for writing readable, maintainable, and professional code.",
    coverImage: "",
    rating: 4.9,
    price: 699,
    status: "Available",
    featured: true,
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    genre: "Business",
    description: "Lessons about money, investing, and financial independence.",
    coverImage: "",
    rating: 4.6,
    price: 450,
    status: "Available",
    featured: false,
  },
  {
    title: "Ikigai",
    author: "Héctor García",
    genre: "Self-Help",
    description: "A book about finding purpose and joy in everyday life.",
    coverImage: "",
    rating: 4.5,
    price: 350,
    status: "Available",
    featured: false,
  },
];

export default books;